baseURL: "https://dakshpareek.github.io/portfolio/"
relativeURLs: true
canonifyURLs: true
languageCode: en-us
title: "Daksh Pareek"
theme: hugo-ivy
ignoreFiles: ["\\.Rmd$", "\\.Rmarkdown$", "_cache$"]
preserveTaxonomyNames: true
publishDir: "docs"
footnotereturnlinkcontents: ↩



permalinks:
  note: /note/:year/:month/:day/:slug/
  post: /post/:year/:month/:day/:slug/

menu:
  main:
    - name: "Home"
      url: "/"
      weight: 1

params:
  description: "Welcome to my personal portfolio website, showcasing my projects and blogs."
  footer: "&copy; [Daksh Pareek](https://daksh.be) 2018-{Year} | [Github](https://github.com/dakshpareek)"
  highlightjsLang: ["latex"]
  highlightjsTheme: "github"
  highlightjsVersion: "11.7.0"

markup:
  highlight:
    codeFences: false
  goldmark:
    renderer:
      unsafe: true
